character_sprites = [
    {"name": "Blue",    "sprite": "https://archives.bulbagarden.net/media/upload/f/fd/Spr_HGSS_Blue.png"},
    {"name": "Red",     "sprite": "https://archives.bulbagarden.net/media/upload/e/e8/Spr_HGSS_Red.png"},
    {"name": "Barry",   "sprite": "https://archives.bulbagarden.net/media/upload/d/d5/Spr_Pt_Barry.png"},
    {"name": "Cynthia", "sprite": "https://archives.bulbagarden.net/media/upload/8/83/Spr_B2W2_Cynthia.png"},
    {"name": "Nate",    "sprite": "https://archives.bulbagarden.net/media/upload/c/cd/Spr_B2W2_Nate.png"},
    {"name": "Hilda",   "sprite": "https://archives.bulbagarden.net/media/upload/b/b7/Spr_B2W2_Hilda_2.png"},
    {"name": "Rosa",    "sprite": "https://archives.bulbagarden.net/media/upload/b/b5/Spr_B2W2_Rosa.png"},
    {"name": "Hilbert","sprite": "https://archives.bulbagarden.net/media/upload/a/a0/Spr_B2W2_Hilbert.png"},
    {"name": "PT-Lucas",   "sprite": "https://archives.bulbagarden.net/media/upload/6/6b/Spr_Pt_Lucas.png"},
    {"name": "PT-Dawn",    "sprite": "https://archives.bulbagarden.net/media/upload/d/d6/Spr_Pt_Dawn.png"},
    {"name": "Leaf",    "sprite": "https://archives.bulbagarden.net/media/upload/0/03/FRLG_Leaf_Intro.png"},
    {"name": "Ethan",   "sprite": "https://archives.bulbagarden.net/media/upload/a/a5/Spr_HGSS_Ethan.png"},
    {"name": "Lyra",    "sprite": "https://archives.bulbagarden.net/media/upload/2/2f/Spr_HGSS_Lyra.png"},
    {"name": "Brendan","sprite": "https://archives.bulbagarden.net/media/upload/e/e6/Spr_E_Brendan.png"},
    {"name": "May",     "sprite": "https://archives.bulbagarden.net/media/upload/a/a4/Spr_E_May.png"},
    {"name": "Lance",   "sprite": "https://archives.bulbagarden.net/media/upload/a/ae/Spr_B2W2_Lance.png"},
    {"name": "Steven",  "sprite": "https://archives.bulbagarden.net/media/upload/4/42/Spr_B2W2_Steven.png"},
    {"name": "N",       "sprite": "https://archives.bulbagarden.net/media/upload/a/a0/Spr_BW_N.png"},
    {"name": "DP-Lucas",   "sprite": "https://archives.bulbagarden.net/media/upload/9/9d/Spr_DP_Lucas.png"},
    {"name": "DP-Dawn",    "sprite": "https://archives.bulbagarden.net/media/upload/0/00/Spr_DP_Dawn.png"},
]